// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simple_Game_Store_WEB_API.Data;

#nullable disable

namespace Simple_Game_Store_WEB_API.Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    partial class GameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simple_Game_Store_WEB_API.DTOs.GameDetailsDTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("GenreID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("GameDetailsDTO");
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("GenreID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.HasIndex("GenreID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            GenreID = 1,
                            Name = "Gta 5",
                            Price = 59.99m,
                            ReleaseDate = new DateOnly(2013, 9, 17)
                        },
                        new
                        {
                            ID = 2,
                            GenreID = 1,
                            Name = "Watch Dogs 1",
                            Price = 39.99m,
                            ReleaseDate = new DateOnly(2014, 5, 26)
                        },
                        new
                        {
                            ID = 3,
                            GenreID = 2,
                            Name = "Cities: Skylines",
                            Price = 29.99m,
                            ReleaseDate = new DateOnly(2015, 3, 10)
                        },
                        new
                        {
                            ID = 4,
                            GenreID = 8,
                            Name = "Fran Bow",
                            Price = 4.99m,
                            ReleaseDate = new DateOnly(2015, 8, 27)
                        },
                        new
                        {
                            ID = 5,
                            GenreID = 8,
                            Name = "Cry of Fear",
                            Price = 0m,
                            ReleaseDate = new DateOnly(2013, 4, 25)
                        },
                        new
                        {
                            ID = 6,
                            GenreID = 10,
                            Name = "Sally Face",
                            Price = 14.99m,
                            ReleaseDate = new DateOnly(2016, 8, 16)
                        },
                        new
                        {
                            ID = 7,
                            GenreID = 8,
                            Name = "Silent Hill 2 Remake",
                            Price = 29.99m,
                            ReleaseDate = new DateOnly(2024, 10, 8)
                        });
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Action-Adventure"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Management"
                        },
                        new
                        {
                            ID = 3,
                            Name = "RPG"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Simulation"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Strategy"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Sports"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Puzzle"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Action"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.UserGame", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("GameID")
                        .HasColumnType("integer");

                    b.Property<int>("LibraryID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserLibraryID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("UserLibraryID");

                    b.ToTable("UserGame");
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.UserLibrary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserLibraries");
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.Game", b =>
                {
                    b.HasOne("Simple_Game_Store_WEB_API.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.UserGame", b =>
                {
                    b.HasOne("Simple_Game_Store_WEB_API.DTOs.GameDetailsDTO", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Simple_Game_Store_WEB_API.Entities.UserLibrary", "UserLibrary")
                        .WithMany("Games")
                        .HasForeignKey("UserLibraryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("UserLibrary");
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.UserLibrary", b =>
                {
                    b.HasOne("Simple_Game_Store_WEB_API.Entities.User", "OwnerUser")
                        .WithOne("UserLibrary")
                        .HasForeignKey("Simple_Game_Store_WEB_API.Entities.UserLibrary", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.User", b =>
                {
                    b.Navigation("UserLibrary")
                        .IsRequired();
                });

            modelBuilder.Entity("Simple_Game_Store_WEB_API.Entities.UserLibrary", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
